#!/bin/bash

while getopts ":s:m" opt; do
  case $opt in
    s)
      config_service="$OPTARG";;
    m)
      only_modified=true;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

oldIFS="$IFS" # store current value of IFS
IFS=':'

for path in `printenv CONFIG_DIR`; do
  if [[ ! -z "$config_service"  ]]; then
    configure_directory $path -s "$config_service"
  elif [[ "$only_modified" == true ]]; then
    configure_directory $path -m
  else
    find /etc/nginx/conf.d ! -name 'default.conf' -type f -exec rm -f {} \;
    configure_directory $path
  fi
done

IFS="$oldIFS" # restore IFS