// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Files            string
	NginxConfigFiles string
	Services         string
}{
	Files:            "files",
	NginxConfigFiles: "nginx_config_files",
	Services:         "services",
}
